Bookstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from Bookstore.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", HomeView.as_view(), name="home"),
    path("", include("books.urls")),
    path("", include("accounts.urls")),
    path("", include("books.api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt import views as jwt_views

from books.api.api_views import AuthorViewSet, BookViewSet, GenreViewSet

router = DefaultRouter()
router.register(r"books", BookViewSet)
router.register(r"authors", AuthorViewSet)
router.register(r"genres", GenreViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path(
        "api/token/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "api/token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"
    ),
]

books/urls.py
from django.urls import path

from books.views import (AuthorCreateView, AuthorDeleteView, AuthorListView,
                         AuthorUpdateView, BookCreateView, BookDeleteView,
                         BookDetailView, BookListView, BookListViewDF,
                         BookUpdateView, GenreCreateView, GenreDeleteView,
                         GenreListView, GenreUpdateView)

urlpatterns = [
    path("bookstore/books/", BookListView.as_view(), name="bookstore"),
    path("bookstore/book/add-book", BookCreateView.as_view(), name="book-add"),
    path("bookstore/book/<int:pk>/", BookDetailView.as_view(), name="book-details"),
    path(
        "bookstore/book/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"
    ),
    path(
        "bookstore/book/<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"
    ),
    path("bookstore/author/create/", AuthorCreateView.as_view(), name="author-add"),
    path("bookstore/authors/", AuthorListView.as_view(), name="authors"),
    path(
        "bookstore/author/<int:pk>/update",
        AuthorUpdateView.as_view(),
        name="author-update",
    ),
    path(
        "bookstore/author/<int:pk>/delete",
        AuthorDeleteView.as_view(),
        name="author-delete",
    ),
    path("bookstore/genre/create/", GenreCreateView.as_view(), name="genre-add"),
    path("bookstore/genres/", GenreListView.as_view(), name="genres"),
    path(
        "bookstore/genre/<int:pk>/update/",
        GenreUpdateView.as_view(),
        name="genre-update",
    ),
    path(
        "bookstore/genre/<int:pk>/delete/",
        GenreDeleteView.as_view(),
        name="genre-delete",
    ),
    path("bookstore/books-df/", BookListViewDF.as_view(), name="bookstore_df"),
]

books/models/book.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name


class Book(models.Model):
    title = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    image = models.ImageField(
        upload_to="book_pics", default="default.png", help_text="Min. size 300x300"
    )
    publication_year = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=1)
    genre = models.ForeignKey(Genre, on_delete=models.DO_NOTHING, related_name="books")
    authors = models.ManyToManyField(Author, related_name="books")
    in_stock = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.title

books/forms/book.py
from django.forms import (DecimalField, ImageField, ModelForm,
                          ModelMultipleChoiceField)

from books.models import Author, Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

    rating = DecimalField(decimal_places=1, min_value=1.0, max_value=10)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if isinstance(visible.field, ImageField):
                pass
            else:
                visible.field.widget.attrs["class"] = "form-control"

books/views/books_filters.py
import django_filters
from django.forms import CheckboxInput
from django_filters.widgets import RangeWidget

from books.models import Author, Book, Genre

# based on django filters


class BookFilter(django_filters.FilterSet):

    CHOICES = (("ascending", "Ascending"), ("descending", "Descending"))

    title = django_filters.CharFilter(
        label="Title", field_name="title", lookup_expr="icontains"
    )

    genre = django_filters.ModelChoiceFilter(
        label="Genre", queryset=Genre.objects.all(), field_name="genre"
    )
    author = django_filters.ModelChoiceFilter(
        label="Author", queryset=Author.objects.all(), field_name="authors"
    )

    ordering = django_filters.ChoiceFilter(
        label="Ordering by Price", choices=CHOICES, method="filter_by_order"
    )

    rating = django_filters.RangeFilter(
        label="Rating Between",
        field_name="rating",
        widget=RangeWidget(attrs={"class": "textinput textInput form-control"}),
    )

    class Meta:
        model = Book
        fields = ["title", "genre", "author", "rating"]

    @staticmethod
    def filter_by_order(queryset, name, value):
        expression = "price" if value == "ascending" else "-price"
        return queryset.order_by(expression)


# own filters
def filter_rating(min_rating, max_rating):
    if min_rating and not max_rating:
        context = Book.objects.filter(rating__gte=min_rating)
    elif max_rating and not min_rating:
        context = Book.objects.filter(rating__lte=max_rating)
    else:
        context = Book.objects.filter(rating__gte=min_rating, rating__lte=max_rating)
    return context


def filter_books(
    genre: str = None,
    title: str = None,
    author: str = None,
    max_rating: str = None,
    min_rating: str = None,
):
    context = Book.objects.none()
    if author:
        first_name = author.split(" ")[0]
        last_name = author.split(" ")[1]
        author = Author.objects.get(first_name=first_name, last_name=last_name)
    if genre:
        genre = Genre.objects.get(name=genre)

    if any([genre, title, author, max_rating, min_rating]):
        if all([genre, title, author, max_rating, min_rating]):
            context = Book.objects.filter(
                title__icontains=title, genre=genre, authors=author
            )
            context = context.filter(rating__gte=min_rating, rating__lte=max_rating)

        elif genre:
            context = Book.objects.filter(genre=genre)

        elif title:
            context = Book.objects.filter(title__icontains=title)

        elif author:
            context = Book.objects.filter(authors=author)

        elif min_rating or max_rating:
            return filter_rating(min_rating, max_rating)

    if len(context.all()) == 0:
        return Book.objects.none()

    return context

books/views/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from books.models import Book, Genre, Author
from books.forms import BookForm



class BookListView(ListView):
    model = Book
    template_name = "books/books.html"
    context_object_name = "books"
    ordering = ["title"]
    paginate_by = 6

    def get_queryset(self):
        genre = self.request.GET.get('genre')
        author = self.request.GET.get('author')
        if genre:
            new_context = self.model.objects.filter(genre=Genre.objects.get(name=genre))
            return new_context
        elif author:
            first_name = author.split(' ')[0]
            last_name = author.split(' ')[1]
            new_context = self.model.objects.filter(author=Author.objects.get(first_name=first_name,
                                                                              last_name=last_name))
            return new_context
        else:
            return super().get_queryset()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['authors'] = Author.objects.all()
        return context

    def get_paginate_by(self, queryset):
        super().get_paginate_by(queryset)
        return self.request.GET.get('paginate_by', self.paginate_by)


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = "books/book_form.html"
    success_url = reverse_lazy('bookstore')


class BookDetailView(DetailView):
    model = Book
    template_name = "books/book_detail.html"


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = "books/book_form.html"

    def get_success_url(self):
        return reverse_lazy('book-detail', kwargs={'pk': self.request.object.pk})


class BookDeleteView(DeleteView):
    model = Book
    template_name = "books/book_delete.html"
    success_url = reverse_lazy('books')

books/views/views_author.py
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from books.models import Author


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class AuthorCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Author
    template_name = "books/form_author_genre.html"
    fields = "__all__"
    permission_required = "books.add_author"

    def get_success_url(self):
        messages.success(self.request, "New author successfully added")
        return reverse_lazy("authors")


class AuthorListView(ListView):
    model = Author
    template_name = "books/authors_list.html"
    context_object_name = "authors"


class AuthorUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Author
    template_name = "books/form_author_genre.html"
    fields = "__all__"
    success_url = reverse_lazy("authors")
    permission_required = "books.change_author"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Author data successfully changed")
        return super().form_valid(form)


class AuthorDeleteView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Author
    template_name = "books/author_confirm_delete.html"

    def get_success_url(self):
        messages.error(self.request, "Author data successfully deleted")
        return reverse_lazy("authors")

books/views/views_book.py
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from books.forms import BookForm
from books.models import Author, Book, Genre

from .books_filters import BookFilter, filter_books


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    template_name = "books/books.html"
    context_object_name = "books"
    ordering = ["title"]
    paginate_by = 6

    def get_queryset(self):
        genre = self.request.GET.get("genre")
        author = self.request.GET.get("author")
        title = self.request.GET.get("title")
        min_rating = self.request.GET.get("rating-min")
        max_rating = self.request.GET.get("rating-max")
        if any([genre, author, title, min_rating, max_rating]):
            context = filter_books(
                genre=genre,
                author=author,
                title=title,
                max_rating=max_rating,
                min_rating=min_rating,
            )
            return context
        else:
            return super().get_queryset()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["genres"] = Genre.objects.all()
        context["authors"] = Author.objects.all()
        return context

    def get_paginate_by(self, queryset):
        return self.request.GET.get("paginate_by", self.paginate_by)


# list view created for Django Filters
class BookListViewDF(LoginRequiredMixin, ListView):
    model = Book
    template_name = "books/books_df.html"
    ordering = ["title"]
    paginate_by = 6

    def paginate_filter_queryset(self):
        context = BookFilter(self.request.GET, queryset=self.get_queryset()).qs
        paginate_by = self.get_paginate_by(context)
        page = self.request.GET.get("page", 1)

        paginator = Paginator(context, paginate_by)

        try:
            paginated_filter = paginator.page(page)
        except PageNotAnInteger:
            paginated_filter = paginator.page(1)
        except EmptyPage:
            paginated_filter = paginator.page(paginator.num_pages)
        return paginated_filter

    def get_paginate_by(self, queryset):
        if self.request.GET.get("paginate_by") == "":
            return self.paginate_by
        return self.request.GET.get("paginate_by", self.paginate_by)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context["paginated_filter"] = self.paginate_filter_queryset()
        return context


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = "books/book_form.html"
    success_url = reverse_lazy("bookstore")
    permission_required = "books.add_book"


class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = "books/book_detail.html"


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm
    template_name = "books/book_form.html"
    permission_required = "books.change_book"

    def get_success_url(self):
        return reverse_lazy("book-detail", kwargs={"pk": self.request.object.pk})

    def get_permission_denied_message(self):
        return messages.error(
            self.request, "You have no permission to update this book!"
        )

    def handle_no_permission(self):
        self.get_permission_denied_message()
        return HttpResponseRedirect(reverse_lazy("bookstore"))


class BookDeleteView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Book
    template_name = "books/book_delete.html"
    success_url = reverse_lazy("books")

books/views/views_genre.py
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from books.models import Genre


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class GenreCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Genre
    template_name = "books/form_author_genre.html"
    fields = "__all__"
    permission_required = "books.add_genre"

    def get_success_url(self):
        messages.success(self.request, "New genre successfully added")
        return reverse_lazy("genres")


class GenreListView(ListView):
    model = Genre
    template_name = "books/genre_list.html"
    context_object_name = "genres"


class GenreUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Genre
    template_name = "books/form_author_genre.html"
    fields = "__all__"
    success_url = reverse_lazy("genres")
    permission_required = "books.change_genre"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Genre data successfully changed")
        return super().form_valid(form)


class GenreDeleteView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Genre
    template_name = "books/genre_confirm_delete.html"

    def get_success_url(self):
        messages.error(self.request, "Genre successfully deleted")
        return reverse_lazy("genres")

books/templates/books/author_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section mt-5">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Author</legend>
                <h5>Are you sure you want to delete this book "{{ object.full_name }}"</h5>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Delete</button>
                <a class="btn btn-secondary" href="{% url 'authors' %}">Cancel</a>
            </div>
        </form>
    </div>

{% endblock content %}

books/templates/books/authors_list.html
{% extends "base.html" %}
{% load has_group %}

{% block content %}
    <div class="col-md-9">
         <article class="media content-section">


             <table class="table table-bordered table-sm mt-5">
                 <thead>
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Books on Stock</th>
                        <th scope="col">Edit / Delete</th>
                    </tr>
                 </thead>
                 <tbody>
                    {% for author in authors %}
                        <tr>
                            <td>{{ author.first_name }}</td>
                            <td>{{ author.last_name }}</td>
                            <td>{{ author.books.all|length }}</td>
                            <td>
                                {% if user|has_group:"Moderators" or user.is_staff %}
                                    <a href="{% url 'author-update' author.pk %}" class="btn btn-light btn-sm mr-2">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                {% else %}
                                <a class="btn btn-light btn-sm" href="#">
                                    <i class="fas fa-times"></i>
                                </a>
                                {% endif %}
                                {% if user.is_stuff or user.is_superuser %}
                                    <a class="btn btn-light btn-sm" href="{% url 'author-delete' author.pk %}">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                {% else %}
                                    <a class="btn btn-light btn-sm" href="#">
                                        <i class="fas fa-times"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                 </tbody>
             </table>
         </article>



    </div>
{% endblock %}

books/templates/books/book_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section mt-5">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Book</legend>
                <h5>Are you sure you want to delete this book "{{ object.title }}"</h5>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Delete</button>
                <a class="btn btn-secondary" href="{% url 'bookstore' %}">Cancel</a>
            </div>
        </form>
    </div>

{% endblock content %}

books/templates/books/book_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="col-md-11">
         <article class="media content-section">
            <div class="media-body">
                <hr>
               <div class="article-metadata">
                   <h5 class="book-title">Title: {{ object.title }}</h5>
                   <span class="book-author">Author: {{ object.authors.all.0 }}</span>
               </div>
                <hr>
                <img class="book-cover" src="{{ object.image.url }}" width="200" height="300"/>
                <p>Description:</p>
                <p class="book-description">{{ object.description }}</p>

                <div class="book-data">
                    <hr>
                    <p>Genre: {{ object.genre }}</p>
                    <p>Price: {{ object.price }} PLN</p>
                    <p>Publication Year: {{ object.publication_year }}</p>
                    <p>Rating: {{ object.rating }}/10</p>
                </div>
            </div>

         </article>

         <hr>

         {% if user.is_authenticated %}
             <div class="buttons-panel">
                <a class="btn btn-primary" href="{% url 'book-update' object.pk %}" role="button">Update</a>
                 {% if user.is_staff %}
                    <a class="btn btn-danger" href="{% url 'book-delete' object.pk %}" role="button">Delete</a>
                 {% endif %}
             </div>
        {% endif %}
    </div>
{% endblock %}

books/templates/books/book_form.html
{% extends "base.html" %}

{% block content %}
    <div class="book-form-content col-md-12">
      <form class="book_form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
          {{ form.title.errors }}
          <label for="{{ form.title.id_for_label }}">Title:</label>
          {{ form.title }}
        </div>
        <div id="form-book" class="row">
              <div class="col">
                <div class="form-group">
                  {{ form.genre.errors }}
                  <label for="{{ form.genre.id_for_label }}">Genre:</label>
                  {{ form.genre }}
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  {{ form.rating.errors }}
                  <label for="{{ form.rating.id_for_label }}">Rating:</label>
                  {{ form.rating }}
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  {{ form.publication_year.errors }}
                  <label for="{{ form.publication_year.id_for_label }}">Pub.Year:</label>
                  {{ form.publication_year }}
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  {{ form.price.errors }}
                  <label for="{{ form.price.id_for_label }}">Price:</label>
                  {{ form.price }}
                </div>
              </div>
        </div>
        <div class="form-group">
          {{ form.description.errors }}
          <label for="{{ form.description.id_for_label }}">Description:</label>
          {{ form.description }}
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    {{ form.image.errors }}
                    <label for="{{ form.image.id_for_label }}">Book Cover:</label>
                    {{ form.image }}
                </div>
            </div>
        <div class="col">
            <div class="form-group">
              {{ form.authors.errors }}
              <label for="{{ form.authors.id_for_label }}">Author:</label>
              <select name="authors" class="form-control" id="id_authors">
                {% for value,author in form.authors.field.choices %}
                    <option value="{{ value }}">{{ author }}</option>
                {% endfor %}
              </select>
            </div>
        </div>
        </div>


        <input type="submit" value="Submit" class="btn btn-primary"/>

      </form>
  </div>
{% endblock %}

books/templates/books/books.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}



    <div class="books col-md-9">
        <div id="book-list" class="row">
            {% for book in books %}
                <div class="column">
                    <div class="jumbotron">
                        <a class="book-detail-a" href="{% url 'book-details' book.pk %}">{{ book.title|truncatechars:25 }}</a>
                        <img src="{{ book.image.url }}" width="200" height="300"/>
                        <div class="book-price-rating">
                            <p>Price {{ book.price }} PLN</p>
                            <p>Rating {{ book.rating }}/10</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="sidebar col-md-3 mt-5">
        <div class="jumbotron">
            <h5>Filters</h5>
            <form method="get">
                <div class="form-group">
{#                    {% csrf_token %}#}
                    <label for="pagination">Books on page</label>
                    <select id="pagination" name="paginate_by" class="form-control">
                        <option value="6">6</option>
                        <option value="1">1</option>
                        <option value="3">3</option>
                        <option value="9">9</option>
                        <option value="12">12</option>
                        <option value="18">18</option>
                    </select>
                    <label for="title">Title</label>
                    <input id="title" name="title" class="form-control"/>
                    <label for="author" class="mt-2">Author</label>
                    <select id="author" name="author" class="form-control">
                        <option></option>
                        {% for author in authors %}
                            <option>{{ author }}</option>
                        {% endfor %}
                    </select>

                    <label for="genre" class="mt-2">Genre</label>
                    <select id="genre" name="genre" class="form-control">
                        <option></option>
                        {% for genre in genres %}
                            <option>{{ genre }}</option>
                        {% endfor %}
                    </select>

                    <label for="min-rating">Min. Rating</label>
                    <input id="min-rating" name="rating-min" class="form-control"/>
                    <label for="max-rating">Max. Rating</label>
                    <input id="max-rating" name="rating-max" class="form-control"/>

                    <button type="submit" class="btn btn-primary mt-4">Submit</button>
                </div>
            </form>

        </div>
    </div>


    <div class="buttons-paginate">
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>



{% endblock %}

books/templates/books/form_author_genre.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="common-form">
         <div class="content-section">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Add</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Add</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

books/templates/books/genre_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section mt-5">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Genre</legend>
                <h5>Are you sure you want to delete this genre "{{ object.name }}"</h5>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Delete</button>
                <a class="btn btn-secondary" href="{% url 'genres' %}">Cancel</a>
            </div>
        </form>
    </div>

{% endblock content %}